#Colors config which is imported in alacritty.yml
#cool color schemes: https://gogh-co.github.io/Gogh/
#current scheme: Everblush

colors:
  primary:
    background: "#1a1a1a"
    foreground: "#FDF0ED"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"
  footer_bar:
    background: "#282a36"
    foreground: "#f8f8f2"
  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "#44475a"
  normal:
    black: "#232A2D"
    red: "#E57474"
    green: "#8CCF7E"
    yellow: "#E5C76B"
    blue: "#67B0E8"
    magenta: "#C47FD5"
    cyan: "#6CBFBF"
    white: "#B3B9B8"
  bright:
    black: "#2D3437"
    red: "#EF7E7E"
    green: "#96D988"
    yellow: "#F4D67A"
    blue: "#71BAF2"
    magenta: "#CE89DF"
    cyan: "#67CBE7"
    white: "#BDC3C2"
